### ISSUE TITLE
antivirus/malware software gets in the way

### ISSUE THREAD

**Issue by raphywink** [rstudio/R-Websockets#13]
Hi guys,

we are currently using this great package in one of our projects. I just wanted to give you guys a heads up that [this](http://help.agilebits.com/1Password_Windows/antivirus-configuration.html) also applies to the R-Websockets package. It caused us quite a headache seeing as it results in some quite unpredictable behaviour (server suddenly starts responding after X calls to it and so on...).

Hope it is ok that i posted it as an issue

regards

Raphael

**Comment by flying-sheep** [comment]
sure it’s OK, but please report it as false positive with the AV companies. it’s their bug.

**Comment by raphywink** [comment]
will do and thanks for the reply!
