### ISSUE TITLE
WebSocket spec rev 8 support

### ISSUE THREAD

**Issue by th0br0** [rstudio/R-Websockets#2]
Hey there,

I just stumbled upon this package (great job btw!) as I need some websocket functionality in R.
However, the package -- as it is in git HEAD -- doesn't work OOTB with modern chrome releases (got Chrome 14 beta here).

The newest libwebsocket git HEAD, however, does support rev 7.
Between rev 7 and rev 8 there were no real changes done to the protocol itself (I believe) therefore, it can easily be hacked into working with rev 8, too :)

Would be great if you could add support for rev 08 out of the box!

**Comment by th0br0** [comment]
Forgot the gist: https://gist.github.com/1206104

**Comment by bwlewis** [comment]
Thanks, yes I'll update that as soon as possible.
On Sep 9, 2011 8:39 AM, "Andreas Osowski" <
reply@reply.github.com>
wrote:

**Comment by bwlewis** [comment]
Here is an update: We are working on supporting both draft-ietf-hybi-thewebsocketprotocol-10 and draft-ietf-hybi-thewebsocketprotocol-00, including binary transmission and compression. We decided to do a significant revamping of the code and will drop our dependence on libwebsockets. The new package will be ready this week.

**Comment by th0br0** [comment]
That's great news!
Thanks for the info.
I'm looking forward to the update.

**Comment by th0br0** [comment]
Do you have an update on this?
I do quite need the update in my current project :D

Thanks

**Comment by bwlewis** [comment]
Hi Andreas,

Sorry for the latency,  I was unable to work on much last week. The
current github version is quite close to finished. It supports most
draft IETF protocols in use and now Windows too. We are in process of
checking things out more carefully on Mac OS X right now.

Our plan is this: I am re-writing the vignette now, which is out of
date. Then we will do another round of bug testing on all platforms.
Then submit to CRAN. I think the current github version is OK to use,
and will update you when the CRAN version is released.

The major changes are:
1. everything associated with COOKIES is gone.
2. The odd and indirect broadcast approach used by the C libwesockets
   library has been replaced by a much simpler websocket_broadcast
   function.

Cheers,

Bryan

On Fri, Sep 9, 2011 at 8:39 AM, Andreas Osowski
reply@reply.github.com
wrote:

**Comment by th0br0** [comment]
Ok, awesome!
Thanks for the update, I'll integrate the updated package into my application this week then and get back to you with any bugs I find :)
- Andreas

**Comment by bwlewis** [comment]
Hi Andreas,

  There was a bug in the old -00 protocol handshake that affected some
browsers. It was fixed today along with some miscellaneous
enhancements that protect against some malformed client input. It's
getting close...

I put one of the demos up on an EC2 instance running live with R-2.13.1 here:

http://204.236.195.60:7681/

Best,

Bryan

On Sun, Oct 2, 2011 at 3:45 PM, Andreas Osowski
reply@reply.github.com
wrote:

**Comment by bwlewis** [comment]
Hi Andreas,

  The latest git version of websockets is very close to what will
appear on CRAN. It includes _lots_ of under the hood improvements, as
well as a websocket client function that supports multiple protocols.

https://github.com/bwlewis/R-Websockets

We expect this will be pushed to CRAN on Sunday.

--Bryan

On Fri, Sep 9, 2011 at 8:39 AM, Andreas Osowski
reply@reply.github.com
wrote:
