### ISSUE TITLE
Anyway of shutting down the server context?

### ISSUE THREAD

**Issue by timyates** [rstudio/R-Websockets#4]
An opposing function to `createContext` that shuts down the server socket and cleans up (kills) all client connections would be handy to have...

**Comment by bwlewis** [comment]
Dear Tim,

Use websocket_close on the server object. Another approach is to
simply delete the server object, but that might require a subsequent
gc() to fully terminate open client connections.

Best,

Bryan

On Fri, Nov 18, 2011 at 10:24 AM, Tim Yates
reply@reply.github.com
wrote:

**Comment by timyates** [comment]
Hi Bryan,

Fantastic...that works :-)  I didn't realise it could be called on the server object :-)

I've got a quick demo working now with Rook handling all my static JS files and R-websockets handling the interaction (and main html page, so that I don't get XOrigin errors)

And this fixes my `demo()` `CTRL-C` `demo()` issue I was having with ports already open (I didn't know how to shut it down in the interrupt handler) :-)

Thanks again!

I'll close this issue now, as it wasn't one ;-)

Tim
